### ISSUE TITLE
Add overview paragraph

### ISSUE THREAD

**Issue by glyn** [iliabylich/writing-bindings-upside-down#2]
I like this project and [the associated article](https://ilyabylich.svbtle.com/writing-bindings-upside-down), but it would be really great to include a paragraph in the article and in the project README which clarifies what the objectives are. Do you want to call C code from Rust, Rust code from C, both, or what? Similarly for the other languages. I'm sure this is perfectly clear if you spend longer reading and scratching your head, but why not make it patently obvious for newcomers? Thanks!

**Comment by iliabylich** [comment]
The article (and the repo) is about calling Rust from multiple languages (C/C++/Ruby/Node.JS). It is mentioned in the first sentence of the article.

> Quite a long time ago I started writing C/C++/Ruby/Node.JS/WASM bindings for my Rust project. ... I tried multiple ways and found one that ... deserves it’s own article

Thanks for coming, but I don't understand what's missing.

**Comment by glyn** [comment]
I re-read that sentence multiple times, but it's ambiguous (at least to me). E.g. a "C binding for my Rust project" could mean what you intend it to mean. But it could also mean a binding to some C code that my Rust project wants to call. Do you see the ambiguity now?

Anyway, may I suggest a rewording:

> Quite a long time ago I started writing C/C++/Ruby/Node.JS/WASM bindings so I could call my Rust project from those languages.

Or something like that?

**Comment by iliabylich** [comment]
Hmm, no, from my experience "X bindings for Y" means:

+ library Y
+ glue code to make it call-able from language/framework X

But I applied your change, it sounds a bit verbose but definitely more explicit. Thanks.

**Comment by glyn** [comment]
Thank you!

**Comment by glyn** [comment]
fyi promoted your article: https://fosstodon.org/@underlap/107581568118611831
